### ISSUE TITLE
Reseting a non-repeating group which is declared in another journal entry

### ISSUE THREAD

**Issue by IrmatDen** [klaas1979/tablesmith-like#12]
**Describe the bug**
Following the fix in #11, I tried to reference the groups declared in another journal entry, and the parser seems chokes on the reset call or I misunderstand the syntax to use.

**To Reproduce** / **Example Table Showing the Bug**

The following assumes a journal named "motiv.tab" which contains this table:
```
;!MotivationNouns
1,test1
1,test2
1,test3
```

The main table can simply be (in, say, `main.tab`):
```
:Start
1,{Loop~3,[motiv.MotivationNouns]}{Reset~motiv.MotivationNouns}
```

* if I use `{Reset~motiv.MotivationNouns}` it results in this error: `Cannot reset group 'motiv.MotivationNouns' in table 'NpcGenerator', not defined!`
* and if I use `{Reset~[motiv.MotivationNouns]}` then the reset call applies to the "pointed" value; I get the error `Cannot reset group 'test3' in table 'NpcGenerator', not defined!`

**Expected behavior**
Evaluating the table should result in some combination of all 3 test entries, eg `test1test3test2`

**Additional context**
I'm using a subfolder for subtables, this isn't an issue for calls others than Reset it seems. But it could be worth mentionning.

**Comment by klaas1979** [comment]
Reset was only implemented for the same file. Could be that you find more problems in using non repeating groups, as do not have used them myself and so the implementation is basic.

**Comment by IrmatDen** [comment]
Thanks for another fast fix :)
