### ISSUE TITLE
Compatibility w/ FoundryVTT 10

### ISSUE THREAD

**Issue by twright-0x1** [klaas1979/tablesmith-like#14]
Hi, there!  Very interested in using this add-on; however, it doesn't appear to be compatible with FoundryVTT 10.x.  When I attempt to use tablesmith-like, the Tablesmith Parse Errors macro indicates "input is undefined" for all tables.  I'm guessing this is due to incompatibility with Foundry.

Is an update for FoundryVTT 10.x in the offing?

**Comment by klaas1979** [comment]
Have not looked into it. I will try to update the plugin, but it will take some waiting, till I find the time for it.

**Comment by twright-0x1** [comment]
Thanks!

**Comment by Unrhymed** [comment]
Would love to see this updated for V10.  I've used tablesmith for a long time and started using foundry VTT 2 years ago.  I thought I would never have the complexity of tablesmith in foundry but I found this module today.  Honestly like finding gold! somewhere I never thought I would.

**Comment by klaas1979** [comment]
I am about to set up the environment with the new Foundry version. Hope that the changes are not too much. Will notify here, when I am done.

**Comment by klaas1979** [comment]
Please check out the new release and see what is working. Foundry introduced some real changes, so I guess you will find some bugs with things that are not working anymore. My quick testing let me do the most important things. My guess is that the datasets to reach into Foundry objects are not working anymore, but this was just tinkering anyway. The core functionality should work.
