### ISSUE TITLE
Pasting in externally written tables causes errors

### ISSUE THREAD

**Issue by Lyinggod** [klaas1979/tablesmith-like#2]
I am fairly proficient with tablesmith and I write tables in Notepad++ to help with structure, formatting, and debugging. When I paste the files into my Foundry (Forge) journal entry, the HTML modification causes errors with the parser. After the automatic reformatting of my text by the HTML editor, I have to add a <br /> before the table so it looks something like:

<p><br />:Start</p>

This may also be caused because I leave a blank line between tables to help with clarity as my tables can get very large and the tables would be impossible to read without those blank lines.

Example:
:Start
1, [thing1]
2, [thing2]

:thing1
1, stuff

:thing2
1, more stuff

**Comment by klaas1979** [comment]
Blank lines are absolutely no problem. Could you provide more details about the part

>  I have to add a
before the table so it looks something like:

what is the thing you add? A newline or a heading?

**Comment by Lyinggod** [comment]
The thing I added was a `<BR>` however this "fix" wasn't working reliably after I identified it to you, or at least attempted to, as a potential solution.

The error I am receiving is:
![image](https://user-images.githubusercontent.com/16379736/155884419-65503908-368a-4418-9265-838c8d7d39ae.png)

The code as as it appears in Notepad
![image](https://user-images.githubusercontent.com/16379736/155885048-ac9e0b54-db7a-4b03-86b5-aa99a36928c7.png)

The code as it appears after unmodified paste in the journal and the journal converts it to HTML:
```
<p>12-13, Investigator</p>
<p>_|arch=investigator|</p>
<p>14-17, Occultist</p>
<p>_|arch=occultist|</p>
<p>18-20, Soldier</p>
<p>_|arch=soldier|</p>
<p>&nbsp;</p>
<p>:arch_benefits</p>
<p>1,[%arch%_skill]</p>
<p>_{Bold~Gain the Focuses:}{CR~}</p>
<p>_[focus]</p>
<p>_{CR~}{CR~}</p>
<p>_{Bold~Gain the Following belongings:}{CR~}</p>
<p>_[%arch%_stuff]</p>

```

**Comment by klaas1979** [comment]
The new version 1.4.0 should fix the problem. The HTML editor inserts some &nbsp; non-breaking-space characters that need to be included in the parser. An error I could reproduce is fixed with a small change in the parser.
