### ISSUE TITLE
Support for IF in tab file

### ISSUE THREAD

**Issue by TheLaslo** [klaas1979/tablesmith-like#4]
First of all...  
  I love that you did this, I have so many tables that I can pull into foundry.

Ignore the underscore problem, I misread the error, it seems there isn't support for IF

Also ignoring the Status directive could help too.

[Melee Weapons.tab.txt](https://github.com/klaas1979/tablesmith-like/files/8227353/Melee.Weapons.tab.txt)

**Comment by klaas1979** [comment]
Right now the stuff is case sensitive, is the table working in Tablesmith? Right now I have no instance running, as this was my problem after leaving Microsoft as OS.

If it works in Tablesmith, then I need to support case-insensitive Functions. I.e. if, iF, IF, If

**Comment by TheLaslo** [comment]
Yes this table works on Tablesmith.
Is there a general case I should be using?  All caps, all lower for
functions?

**Comment by klaas1979** [comment]
Added case insensitive TS-Functions in new release 1.7.0. Added Status as function as well.
