### ISSUE TITLE
Escaped % creating errors inside functions

### ISSUE THREAD

**Issue by Lyinggod** [klaas1979/tablesmith-like#6]
**Describe the bug**
When placing an escaped non-variable percentage inside a function (ie 10/%), an error is returned.

**To Reproduce**
The following produces an error. This has not been attempted with other functions.
1,|techskill={InputList~1,Select a Tech Skill (10/% bonus), Athletics,Survival}|

**Example Table Showing the Bug**
%techskill%,0

:Start
1,|techskill={InputList~1,Select a Tech Skill (+10/% bonus), Athletics,Survival}|
_%techskill%

**Expected behavior**
Resulting prompt shows "Select a Tech Skill (+10% bonus)"

**Screenshots**

**Environment (please complete the following information):**
Forge-vtt
chrome
Foundry Version 9.266
Tablesmit-like Plugin version: 1.11

**Comment by klaas1979** [comment]
Thank you for the detailed report.

Bug is fixed in new version **1.11.1**
