### ISSUE TITLE
HTML not processing as part of prompt text

### ISSUE THREAD

**Issue by Lyinggod** [klaas1979/tablesmith-like#7]
**Describe the bug**
The ```<br>``` in a prompt command such as InputList does not create a line break with the prompt. This has not been attempted with other TS functions or HTML tags.

**To Reproduce**
Create a InputList line with a ```<br>``` or perhaps other HTML tag inside the text prompt portion of the function.

**Example Table Showing the Bug**
```
%techskill%,0

:Start
1,|techskill={InputList~1,Select a Tech Skill<BR> (+10/% bonus), Athletics,Survival}|
_%techskill%
```

**Expected behavior**
The prompt should appear as follows, notice the line break.
_Select a Tech Skill 
(+10% bonus)_

**Environment (please complete the following information):**
Forge-vtt
chrome
Foundry Version 9.266
Tablesmit-like Plugin version: 1.11

**Additional Context:**
The sample table will create a error unless the /% is removed. This has been addressed in a separate bug report.

**Comment by klaas1979** [comment]
Thank you for the detailed report.

Bug is fixed in new version **1.11.1**
