### ISSUE TITLE
{Dice~} is case sensative

### ISSUE THREAD

**Issue by Lyinggod** [klaas1979/tablesmith-like#9]
**Describe the bug**
{Dice~1D4} generates an error (uppercase "D" in 1D4). {Dice~1d4} does not generate an error (lowercase "d" in 1d4)

**To Reproduce**
Roll dice using {Dice~1D4} with an uppercase "D" in "1D4"

**Example Table Showing the Bug**
:Start
1, {Dice~1D4}

**Expected behavior**
{Dice~1D4} should not generate an error as {Dice~1d4} and {Dice~1D4} should be equivalent.

**Screenshots**

**Environment (please complete the following information):**
- Windows
- Chrome
- Forge (Foundry 9.269)
- Tablesmit-like Plugin version 1.11.0

**Comment by klaas1979** [comment]
Fixed with last Release 1.11.2
